Repository hauertmann-it-consulting/hackman, pull requests merged in 2021-06, with the labels that each got.

#18 Feature/snacks hinzufügen
  src/Components/Snack.tsx
  src/Components/Spielfeld.tsx
  src/SpielfeldLayout.tsx
  src/index.css
Labels: enhancement

#20 Hackman mit Mund + fertige Geister
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Gamefield.tsx
  src/Components/Gate.tsx
  src/Components/Geist.tsx
  src/Components/Ghost.tsx
  src/Components/Hackman.tsx
  src/EventEmitter.tsx
  src/SpielfeldLayout.tsx
  src/index.css
  yarn.lock
Labels: enhancement

#24 Warnung ignorieren
  src/Components/Hackman.tsx
Labels: bug

#29 [ENCHANTMENT] Issue Templates eingebunden und aktualisiert
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: enhancement, good first issue
