Repository hauertmann-it-consulting/hackman, pull requests merged in 2021-08, with the labels that each got.

#38 Closes #26 Geisterbewegung
  README.md
  debug.log
  jest.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/Classes/Character.ts
  src/Classes/GhostCharacter.ts
  src/Components/Gamefield.tsx
  src/Components/Ghost.tsx
  src/Components/Hackman.tsx
  src/Components/Stats.tsx
  src/Interfaces/CharacterProps.ts
  src/SpielfeldLayout.tsx
  src/State/slices/gameFieldSlice.ts
  src/State/store.ts
  src/Tests/Mock/Character.Mock.ts
  src/Tests/Mock/GhostCharacter.Mock.ts
  src/Tests/Mock/TestField.Mock.ts
  src/Tests/UtilityFunctions/CustomInterval.test.ts
  src/Tests/UtilityFunctions/GameFieldService/CanMove/CanMove.test.ts
  src/Tests/UtilityFunctions/GameFieldService/CanMove/GetPossibleDirection.test.ts
  src/Tests/UtilityFunctions/GameFieldService/MoveGhost/MoveGhostTroughPortal.test.ts
  src/Tests/UtilityFunctions/GameFieldService/MoveGhost/MoveGhostUp1.test.ts
  src/Tests/UtilityFunctions/GameFieldService/MoveGhost/MoveGhostUp2.test.ts
  src/Tests/UtilityFunctions/GameFieldService/MoveHackman/MoveHackman.test.ts
  src/Tests/UtilityFunctions/GameFieldService/MoveHackman/MoveHackmanTroughPortal.test.ts
  src/Tests/UtilityFunctions/GetRandomNumber.test.ts
  src/Types/BewegungMoeglich.tsx
  src/Types/Coordinate.ts
  src/Types/Direction.ts
  src/Types/Koordinate.ts
  src/Types/Moveable.tsx
  src/Types/Richtung.ts
  src/UtilityFunctions/CustomInterval.ts
  src/UtilityFunctions/GetRandomNumber.ts
  src/UtilityFunctions/move/CanMove.ts
  src/UtilityFunctions/move/MoveGhost.ts
  src/UtilityFunctions/move/MoveHackman.ts
  src/index.css
  src/index.tsx
  yarn.lock
Labels: enhancement

#42 Feature/höhere punktezahl für größere münzen
  src/State/slices/gameFieldSlice.ts
  src/Types/CoinValue.tsx
  src/UtilityFunctions/move/CanMove.ts
  src/UtilityFunctions/move/MoveHackman.ts
Labels: feature

#47 Fix/dynamische größe
  src/App.tsx
Labels: bug

#48 Überarbeitung des Staging-Systems
  .github/workflows/build-and-deploy-staging.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/main.yml
  .github/workflows/pr-build-master.yml
  .github/workflows/pr-build-staging.yml
  package.json
Labels: bug, feature

#50 Feature/staging deployment workflow (ueberarbeitet)
  .github/workflows/build-and-deploy-staging.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/pr-build-master.yml
  .github/workflows/pr-build.yml
Labels: feature

#51 Feature/staging deployment workflow (ueberarbeitet)
  .github/workflows/build-and-deploy-staging.yml
  .github/workflows/build-and-deploy.yml
  .github/workflows/pr-build-master.yml
  .github/workflows/pr-build.yml
Labels: feature

#52 Feature/hackman nicht erst nach click spielbar
  src/App.tsx
Labels: feature

#60 Portal-bug fixed
  src/State/slices/gameFieldSlice.ts
Labels: bugfix
